#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

	 if [ -f "/usr/local/etc/couchpotato/settings.conf" ]; then
		printf "\nPrevious configuration file found, couchpotato can try to use this file so you keep your settings\n"
              while true; do
    			read -p "Do you want to use the old configuration file? (yes/no) " yn
    			case $yn in
        			yes ) 	mv /usr/local/etc/couchpotato/settings.conf /usr/local/etc/couchpotato/settings.reuse; 
					break;;
        			no )   mv /usr/local/etc/couchpotato/settings.conf /usr/local/etc/couchpotato/settings.old; 
					break;;
        			* ) echo "Please answer yes or no.";;
    			esac
		done
	fi

fi
